## Numpy array and basics

In [3]:
import numpy as np

### Creating array from List

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

1D array:  [1 2 3 4 5]


In [5]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D array: \n", arr_2d)

2D array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [6]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [7]:
np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python array multiplication  [2 4 6]


In [8]:
import time

In [9]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)


 List operation time:  0.08343195915222168


In [10]:
start = time.time()
np_array = np.arange(1000000)
print("\n Numpy operation time: ", time.time() - start)


 Numpy operation time:  0.0030584335327148438


### Creating array from scratch

In [11]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((3, 4))
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
arr = np.linspace(0,1,100)
print(arr)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [26]:
np.random.rand(10)

array([0.35207012, 0.2662314 , 0.73335008, 0.35815439, 0.79336085,
       0.9732992 , 0.02010788, 0.81703323, 0.23765907, 0.53917583])

In [27]:
np.random.randn(10)

array([ 2.03776009,  0.419442  , -0.10554801, -0.93794385,  0.09981326,
        1.07050597, -0.11059708, -0.74808857, -0.37611838, -0.33254735])

In [14]:
full = np.full((2, 2), 7)
print("full array: \n", full)

full array: 
 [[7 7]
 [7 7]]


In [15]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.62116446 0.95179847 0.79980319]
 [0.02461261 0.86496035 0.40799965]]


In [16]:
sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [17]:
vector = np.array([1, 2, 3])
print("Vector:",vector)

Vector: [1 2 3]


In [18]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix:\n",matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


In [19]:
tensor = np.array([[[1, 2], [3,4]],
                   [[5, 6], [7, 8]]])
print("Tensor:\n",tensor)

Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("DType:", arr.dtype)


Shape: (2, 3)
Dimension: 2
Size: 6
DType: int64


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("argmax:", np.argmax(arr))
print("argmin:", np.argmin(arr))
print("max:", np.max(arr))
print("min:", np.min(arr))
print("sum:", np.sum(arr))
print("mean:", np.mean(arr))

argmax: 5
argmin: 0
max: 6
min: 1
sum: 21
mean: 3.5


### Array Reshaping

In [21]:
arr = np.arange(12)
print("Original array",arr)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
reshaped = arr.reshape((3, 4))
print("Reshaped array\n",reshaped)

Reshaped array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
flattened = reshaped.flatten()
print("Flattened array",flattened)

Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
# ravel (returns view instead of copy)
raveled = reshaped.ravel()
print("Raveled array",raveled)

Raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [25]:
# Transpose
transpose = reshaped.T
print("Transposed\n",transpose)

Transposed
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
