## Numpy array and basics

In [3]:
import numpy as np

### Creating array from List

In [6]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

1D array:  [1 2 3 4 5]


In [22]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print("2D array: \n", arr_2d)

2D array: 
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [ ]:
np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python array multiplication  [2 4 6]


In [10]:
import time

In [15]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)


 List operation time:  0.15518712997436523


In [ ]:
start = time.time()
np_array = np.arange(1000000)
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.0032052993774414062


### Creating array from scratch

In [16]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
ones = np.ones((3, 4))
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
full = np.full((2, 2), 7)
print("full array: \n", full)

full array: 
 [[7 7]
 [7 7]]


In [20]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.96566947 0.57299223 0.77676746]
 [0.89914243 0.43645665 0.42277312]]


In [21]:
sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]
