## Numpy Array operations

In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [2 3 4 5 6]
With Step [1 3 5 7]
Negative indexing 8


In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ",arr_2d[1])
print("Entire column: ",arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [4]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

Sorted Array [1 1 2 3 4 5 6 9]


In [5]:
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column\n", np.sort(arr_2d_unsorted, axis = 0))

Sorted 2D array by column
 [[1 1]
 [2 2]
 [3 3]]


### Filter

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [7]:
mask = numbers > 5
print("Numbers greater than 5 ",numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [8]:
indicies = [0, 2, 4]
print(numbers[indicies])

[1 3 5]


In [9]:
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [11]:
# Not do in this way
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print(combined)

[5 7 9]


In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibility

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shape", a.shape == b.shape)

Compatibility shape False


In [14]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print("With new row\n",with_new_row)

With new row
 [[1 2]
 [3 4]
 [5 6]]


In [15]:
original = np.array([[1, 2], [3, 4]])
new_col = np.array([[7], [8]])

with_new_col = np.hstack((original, new_col))
print("With new column\n",with_new_col)

With new column
 [[1 2 7]
 [3 4 8]]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)

print("Array after delection:",deleted)

Array after delection: [1 2 4 5]
